version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: hubunk_postgres
    environment:
      POSTGRES_DB: hubunk_db
      POSTGRES_USER: hubunk_user
      POSTGRES_PASSWORD: hubunk_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "145.223.22.181:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - hubunk_network
    command: postgres -c listen_addresses='*'

volumes:
  postgres_data:
    name: hubunk_postgres_data

networks:
  hubunk_network:
    name: hubunk_network 